### ISSUE TITLE
Load to folio-test from prod user harvester

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/registry-harvester#163]
On production harvester, load to production Symphony as usual, but add loading to folio-test instance of folio.

Make sure fake email address is being used for all users.

**Comment by jgreben** [comment]
Make configurable: fake email email and whether the folio post is run on the symphony server.

**Comment by jgreben** [comment]
Fixed by https://github.com/sul-dlss/registry-harvester/pull/164
